import { type Option } from "@shad"

import { stringsToOptions } from "./option"

export const COUNTRY_OPTIONS: Option[] = stringsToOptions([
  "🇧🇷 Brasil",
  "Alemanha",
  "🇦🇷 Argentina",
  "Aruba",
  "Austrália",
  "Áustria",
  "Azerbaijão",
  "Bahamas",
  "Bangladesh",
  "Barbados",
  "Bélgica",
  "Belize",
  "Bielorússia",
  "Bolívia",
  "Bulgária",
  "Canadá",
  "Chile",
  "China",
  "Colômbia",
  "Coreia do Sul",
  "Costa Rica",
  "Croácia",
  "Cuba",
  "Dinamarca",
  "El Salvador",
  "Equador",
  "Escócia",
  "Eslováquia",
  "Espanha",
  "Finlândia",
  "França",
  "Grécia",
  "Guadalupe",
  "Guatemala",
  "Guiana",
  "Guiana Francesa",
  "Haiti",
  "Holanda",
  "Honduras",
  "Hungria",
  "Índia",
  "Indonésia",
  "Inglaterra",
  "Irlanda",
  "Irlanda do Norte",
  "Itália",
  "Jamaica",
  "Japão",
  "Estados Unidos",
  "Martinica",
  "México",
  "Nicarágua",
  "Noruega",
  "Nova Zelândia",
  "Panamá",
  "Paquistão",
  "Paraguai",
  "País de Gales",
  "Peru",
  "Porto Rico",
  "Portugal",
  "Polônia",
  "Reino Unido",
  "República Dominicana",
  "República Tcheca",
  "Romênia",
  "Rússia",
  "Sérvia",
  "Suécia",
  "Suíça",
  "Suriname",
  "Taiwan",
  "Trinidade e Tobago",
  "Turquia",
  "Ucrânia",
  "Uruaguai",
  "Venezuela",
  "Vietnã",
])
